name: Deploy to Server

on:
 push:
    branches:
      - main # Change this to your default branch if different

jobs:
 deploy:
    runs-on: self-hosted # Ensure this matches your self-hosted runner's label

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to server
      run: |
        sudo cp -r . /www/wwwroot/awstesting.run.place
      shell: bash
